### ISSUE TITLE
train_model.py

### ISSUE THREAD

**Issue by HuinaXu** [lars76/object-localization#6]
Reloaded modules: train_model
Traceback (most recent call last):

  File "<ipython-input-5-bc7e7df9f022>", line 1, in <module>
    runfile('C:/Users/huixu/Desktop/object-localization-0812/train_model.py', wdir='C:/Users/hhh/Desktop/object-localization-0812')

  File "C:\Localdata\Python3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Localdata\Python3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/hhh/Desktop/object-localization-0812/train_model.py", line 122, in <module>
    main()

  File "C:/Users/hhh/Desktop/object-localization-0812/train_model.py", line 118, in main
    train(model, EPOCHS, BATCH_SIZE, PATIENCE, TRAIN_CSV, VALIDATION_CSV, MEAN, STD)

  File "C:/Users/hhh/Desktop/object-localization-0812/train_model.py", line 102, in train
    train_datagen = DataSequence(train_csv, batch_size, mean, std)

  File "C:/Users/hhh/Desktop/object-localization-0812/train_model.py", line 47, in __init__
    for index, (path, x0, y0, x1, y1) in enumerate(reader):

ValueError: not enough values to unpack (expected 5, got 0)

**Comment by HuinaXu** [comment]
This issue happened only when I run the code on Windows with tensorflow 1.10.0. It did not happen when I run code on iOS.

**Comment by lars76** [comment]
You are using an old version of object-localization but a new version of train.csv/validation.csv. Either regenerate the data using the old version, or update train_model to the new version.

**Comment by HuinaXu** [comment]
I tried again using both 08/12 version and latest version running on Windows. I made sure keep the version consistent for generate_dataset.py and train_model.py. However, I got similar issues from both version. 

It seems to me it is windown specific. Also, I could print 5 values instead of 0 from the enumerate(reader) without problem.

**Comment by lars76** [comment]
I only have linux, so I cannot reproduce it. Basically the error just says that there is an empty line in the csv file. Check the constant TRAIN_CSV in train_model.py. The problem might be "../train.csv", just use an absolute path e.g. "C://your_csv.csv"

**Comment by HuinaXu** [comment]
@lars76 , you are right. I deleted the empty rows in the csv file and now it also works on windows.
